// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhENnr5vdDmyVNA3pTQpCgk-eN5bsQXkc',
    appId: '1:842866836206:android:942fccebbf17bfa758a9ff',
    messagingSenderId: '842866836206',
    projectId: 'tugas-besar-apb-siptu',
    storageBucket: 'tugas-besar-apb-siptu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp_6NChCyvtcqXMGqBUOYOPj5ogPj8cKE',
    appId: '1:842866836206:ios:9cab4b2d5fc296bf58a9ff',
    messagingSenderId: '842866836206',
    projectId: 'tugas-besar-apb-siptu',
    storageBucket: 'tugas-besar-apb-siptu.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2LO5Ooxnn0QmnNlBMNf_B9tXsoYWE6jU',
    appId: '1:842866836206:web:bcd39b12f168320c58a9ff',
    messagingSenderId: '842866836206',
    projectId: 'tugas-besar-apb-siptu',
    authDomain: 'tugas-besar-apb-siptu.firebaseapp.com',
    storageBucket: 'tugas-besar-apb-siptu.firebasestorage.app',
    measurementId: 'G-21SHGLSTFB',
  );
}
